### ISSUE TITLE
The file "../../../dataset/preprocess/test_subs_clone.jsonl" can not be found in your dataset and github link...

### ISSUE THREAD

**Issue by liliyae** [CGCL-codes/Attack_PTMC#1]
The file "../../../dataset/preprocess/test_subs_clone.jsonl" can not be found in your dataset and github link... can you help me? Thank you for your interesting work!

**Comment by liliyae** [comment]
and the "attacker_bk" file from which import Style_Attacker, get_code_pairs, get_transfered_code" Thank you!

**Comment by xhdu** [comment]
> The file "../../../dataset/preprocess/test_subs_clone.jsonl" can not be found in your dataset and github link... can you help me? Thank you for your interesting work!

We sincerely apologize for any inconvenience caused to you. We have added this file, which is also used in our baseline  [ALERT](https://github.com/soarsmu/attack-pretrain-models-of-code/tree/main/CodeXGLUE/Clone-detection-BigCloneBench/dataset). You can check the above link to get more information.
In addition, "attacker_bk" should be "attacker", which is a typo.
