### ISSUE TITLE
ModuleNotFoundError: No module named 'utils' for running the attack_mhm.py in folder CodeGPT

### ISSUE THREAD

**Issue by hluu2224** [CGCL-codes/Attack_PTMC#2]
Thank you for your interesting work!
I would like to ask which utils.py you used in attack_mhm.py in folder CodeGPT. I could not be able to locate the utils.py which contains functions: set_seed, build_vocab, etc in the repo.
Thanks again,
Kind regards,

**Comment by xhdu** [comment]
We sincerely apologize for any inconvenience caused to you. We have added this file, which is also available in our baseline [ALERT](https://github.com/soarsmu/attack-pretrain-models-of-code/blob/main/utils.py).

**Comment by hluu2224** [comment]
Thank you so much for the file. Another thing I could raise is that I am still unable to locate the is_valid_identifier() function in the provided utils in ALERT.

Is it possible to upload the corresponding file as well.

Thanks in advance!

**Comment by hluu2224** [comment]
Thank you so much for uploading the file! ^-^
