### ISSUE TITLE
Success rate equals 0 for MHM attack on CodeGPT model

### ISSUE THREAD

**Issue by hluu2224** [CGCL-codes/Attack_PTMC#3]
Hi,

Since I could not find "../../../dataset/preprocess/test_subs_summary_sampled.jsonl" (in attack_mhm.py) available in the repo, I used this file "../../../dataset/preprocess/test_subs_summary.jsonl". Then, I got the success rate is 0.

I would like to ask if it is possible to upload test_subs_summary_sampled.jsonl.

Thank you,

**Comment by xhdu** [comment]
I have added this file. Your success rate of 0 may be caused by other factors, please check carefully.
