### ISSUE TITLE
Some questions for PLBART training and attack

### ISSUE THREAD

**Issue by turtlepig2001** [CGCL-codes/Attack_PTMC#6]
Thanks for your interesting work.

I am facing some problems when trying to train the PLBART .

1. The first problem is: I notice you set the args.model_name_or_path equals to "../../checkpoint_11_100000.pt" both in trainning the PLBART and in attck, but i could not find this file. 
2. The second problem is that the config declaration " config = argparse.Namespace(activation_fn='gelu', adam_betas='(0.9, 0.98)', adam_eps=1e-08, .......)" statement in run.py . i can not understand some parameters here just like 'data='/home/zzr/CodeStudy/Defect-detection/plbart/processed/data-bin''. Are these parameters required during fine-tuning?
3. I notice in the same statement, you set restore_file='/data2/cg/CodeStudy/PLBART/pretrain/checkpoint_11_100000.pt', Should I run this program first to get “checkpoint_11_100000.pt”?
Thank you very much, I am eager to get your answer!

**Comment by xhdu** [comment]
1. You can download from this link: https://1drv.ms/u/s!AnLV9A1xwwEtvSIc11BPvEHO6VcX?e=qp0is7
2. For PLBART training, we completely reused the code from the ISSTA 22 work. You can refer to: https://github.com/ZZR0/ISSTA22-CodeStudy. I believe these parameters do not affect the model training.
3. Please use the file downloaded in the first point.
