### ISSUE TITLE
how to generate the file under the "Attack_PTMC/dataset/preprocess"

### ISSUE THREAD

**Issue by lsrhaha1** [CGCL-codes/Attack_PTMC#8]
I did not find the way to get the data in the path of 'Attack_PTMC/dataset/preprocess',could you please tell me how to obtain these documents? Thanks very much !

**Comment by maple826** [comment]
I have the same problem, did you solve it and how did you do it, thanks a lot!

**Comment by lsrhaha1** [comment]
the data can be generated by ALERT,you can refer to https://github.com/soarsmu/attack-pretrain-models-of-code/tree/main/CodeXGLUE/Defect-detection/preprocess

**Comment by maple826** [comment]
thanks you very much!!!
